### ISSUE TITLE
man path

### ISSUE THREAD

**Issue by grylem** [janstary/ports#1]
Please do path for man page
/usr/local/share/man
instead
/usr/local/man

**Comment by janstary** [comment]
Why?

**Comment by grylem** [comment]
a few reasons:
because there are programs previously installed, because unfortunately you did port not for all programms :) also some people(not me) don't want to install mandoc and wont use makewhathis... etc.
But anyway - thanks

**Comment by janstary** [comment]
What does any of that have to do with where the manpages are installed?

Come to think of it, what exactly do you mean by "do path for man page"?

**Comment by grylem** [comment]
Sorry for my bad English
When i  previously installed some libs/apps manpage installed to /usr/local/share/man/man1(man2 ....)
Also in my case mandoc compiled(for .Xr  ) with path  /usr/local/share/man
Man Reader(gui apps for manpage) uses "whatis" from  /usr/local/share/man
it doesn't matter, it's just a wish ;)

**Comment by janstary** [comment]
> When i previously installed some libs/apps manpage installed to /usr/local/share/man/

None of the ports here do that. Look at `MANDIR` in `defaults.mk`.

> Also in my case mandoc compiled (for .Xr ) with path /usr/local/share/man

What version of mandoc is that?
The [default](http://mandoc.bsd.lv/cgi-bin/cvsweb/configure?rev=1.67&content-type=text/x-cvsweb-markup) `MANPATH` in mandoc is `/usr/share/man:/usr/X11R6/man:/usr/local/man`

Also, what do you mean by "compiled for `.Xr`"?

> Man Reader (gui apps for manpage) uses "whatis" from /usr/local/share/man

There is no way I am putting a GUI manpage reader in here, sorry.

**Comment by grylem** [comment]
for mandoc you can set manpath in configure.local
.Xr - “cross-reference” https://mandoc.bsd.lv/man/mdoc.7.html
this is useful for me when i use ManDrake(https://github.com/sveinbjornt/ManDrake)

**Comment by janstary** [comment]
> for mandoc you can set manpath in configure.local

Yes. So what version of mandoc is it that you are using?
Did you build it yourself, configuring `MANPATH` to use `/usr/local/share/man`?

> .Xr - “cross-reference” https://mandoc.bsd.lv/man/mdoc.7.html

Yes. What does it have to do with `MANPATH`?

> this is useful for me when i use ManDrake(https://github.com/sveinbjornt/ManDrake)

How?

**Comment by grylem** [comment]
> Yes. So what version of mandoc is it that you are using?

v 1.14.4 

> Did you build it yourself, configuring `MANPATH` to use `/usr/local/share/man`?

yes

> How?

example fo command line
with "metaflac.1" in /usr/local/share/man/man1
mandoc -T lint /usr/local/share/man/man1/flac.1
no any error or warning
remove  "metaflac.1"
mandoc -T lint /usr/local/share/man/man1/flac.1
mandoc: /usr/local/share/man/man1/flac.1:417:6: STYLE: referenced manual not found: Xr metaflac 1
[man.zip](https://github.com/janstary/ports/files/2881708/man.zip)

**Comment by janstary** [comment]
> with "metaflac.1" in /usr/local/share/man/man1
> mandoc -T lint /usr/local/share/man/man1/flac.1
> no any error or warning
> remove "metaflac.1"
> mandoc -T lint /usr/local/share/man/man1/flac.1
> mandoc: /usr/local/share/man/man1/flac.1:417:6: STYLE: referenced manual not found: Xr metaflac 1

Ah, right, `mandoc -T lint` will try to find them.

> [man.zip](https://github.com/janstary/ports/files/2881708/man.zip)

Hm, how did your flac instalation end up having the manpages in `/usr/local/share/man`?
The port installs them into `/usr/local/man`.

Also, what installation of flac is this?
The two manpages in the attached zip seem to come from
https://github.com/janstary/manpages/tree/master/flac
but I never pushed them upstream (which uses docbook).

**Comment by grylem** [comment]
> Hm, how did your flac instalation end up having the manpages in `/usr/local/share/man`?
The port installs them into `/usr/local/man`

like other installed without your "port"
./configure --args
make
sudo make install

> Also, what installation of flac is this?
The two manpages in the attached zip seem to come from
https://github.com/janstary/manpages/tree/master/flac
but I never pushed them upstream (which uses docbook).

I corrected and used these 2 manpage only for example for you. You can check them and use if you want. 
Сan you give me you copy docbook2mdoc? I compiled for myself but it never works for flac , wavpack.

**Comment by janstary** [comment]
Don't mix software from these ports and manual installations.
That way, you are asking for inconsistencies like these.

For instance, all the ports install their manpages into `/usr/local/man`,
so that's what's in the default manpath of the mandoc port.

I don't use docbook2mdoc.

**Comment by janstary** [comment]
Ha, `/usr/local/share/man` [is](https://github.com/janstary/ports/blob/master/mandoc/extra-configure.local) in the default manpath of mandoc, as installed by the port.
